// jsfold.h — case tables for jsre's i flag, generated by gen_fold.mjs.
#ifndef pocev_JSFOLD_H
#define pocev_JSFOLD_H

#include <cstddef>
#include <cstdint>

namespace pocev {

struct CanonEntry {
    uint16_t from, to;
};
struct FoldEntry {
    uint32_t from, to;
};

// ES5.1 Canonicalize (non-unicode i mode), BMP. Sorted by from.
extern const CanonEntry kCanonNu[];
extern const size_t kCanonNuCount;

// Fold-class representative (unicode i mode), over all code points.
// foldRep(a) == foldRep(b) iff V8 matches the two case-insensitively.
// Sorted by from.
extern const FoldEntry kFoldRep[];
extern const size_t kFoldRepCount;

uint16_t canonNu(uint16_t c);
uint32_t foldRep(uint32_t cp);

}  // namespace pocev

#endif  // pocev_JSFOLD_H
